### ISSUE TITLE
Clarification for adding files to .gitignore

### ISSUE THREAD

**Issue by svincibo** [brain-life/docs#6]
"You should add config.json to .gitignore as config.json is created at runtime by Brainlife, and we just need this now to test your app."

I'm sure this is due to my limited experience with github, but I'm not sure how to do this step. I assume .gitignore is a text file, essentially, and I gather that it lists files that should be ignored in the push and pull processes. There is not a .gitignore file automatically made in app-helloworld and, consequently, I'm unsure about how to do this. Should I simply make a text file and name it .gitignore? 

Maybe you could provide a link to information about this step as you did with creating a git hub repository?

**Comment by soichih** [comment]
Yes, you can just create a new file with a name `.gitignore`. 

I will add a link to https://help.github.com/articles/ignoring-files/
