### ISSUE TITLE
How to view .gitignore contents

### ISSUE THREAD

**Issue by svincibo** [brain-life/docs#8]
Do I need to download a text editor that works from terminal? I can't seem to open the .gitignore file in the file browser without resetting the defaults on my computer (OSX) to see all hidden files. Even if I did that (and I don't want to do that!), I'd be going on the assumption that I can open .gitignore with a text editor. 

Could you off-handedly recommend a text editor (or whatever is needed) in the documentation? It could save time/trouble. As an example: I decided to brew install gedit. I didn't realize that gedit had several dependencies one of which is python. It's currently overwriting my current version of python for another. There's likely a much easier way!

**Comment by soichih** [comment]
@kithell Do you have comment on this item? I am not sure what would be the best (easiest use) text editor on OSX. User don't really need to setup .gitignore. They can just not commit config.json into the repo, or commit it as part of repo and let Brainlife just overwrite it.

**Comment by soichih** [comment]
I've updated to recommend VS Code.
